version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: rag-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      CHROMA_DIR: /app/data/chroma
    volumes:
      - ./data/chroma:/app/data/chroma
      - ./knowledge:/app/knowledge:ro
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: rag-frontend
    ports:
      - "8501:8501"
    environment:
      BACKEND_URL: http://backend:8000
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
